name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/Yidadaa/ChatGPT-Next-Web.git
        git fetch upstream
        git pull upstream main

    - name: Push Changes
      run: |
        git push
